// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qx.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Qx.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QxMDbContext))]
    partial class QxMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableColumnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentVolumeUl")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.Property<string>("VolumeCapacityUl")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId", "Name")
                        .IsUnique();

                    b.ToTable("consumable_column", (string)null);
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.HasIndex("InventoryId", "Name");

                    b.HasIndex("InventoryId", "TypeId");

                    b.ToTable("consumable", (string)null);
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultIsReusable")
                        .HasColumnType("boolean");

                    b.Property<int?>("DefaultMaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConsumableType");
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.InventoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("XUs")
                        .HasColumnType("double precision");

                    b.Property<double>("YUs")
                        .HasColumnType("double precision");

                    b.Property<double>("ZUs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableColumnEntity", b =>
                {
                    b.HasOne("Qx.Infrastructure.Persistence.Entities.ConsumableEntity", "Consumable")
                        .WithMany("Columns")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableEntity", b =>
                {
                    b.HasOne("Qx.Infrastructure.Persistence.Entities.InventoryEntity", "Inventory")
                        .WithMany("Consumables")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qx.Infrastructure.Persistence.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qx.Infrastructure.Persistence.Entities.ConsumableTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Location");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.ConsumableEntity", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Qx.Infrastructure.Persistence.Entities.InventoryEntity", b =>
                {
                    b.Navigation("Consumables");
                });
#pragma warning restore 612, 618
        }
    }
}
