@startuml
- Client
partition "**HardwareGateway** (gRPC Service)" {
    - HardwareGateway (facade)
    switch (HardwareGatewayRouter)
    case ( ICB )
        :IcbAdapter;
        :IcbClient;
    case ( Pipettor )
        :PipettorAdapter;
        :PipettorClient;
    case ( Camera )
        :CameraAdapter;
        :CameraClient;
    case ()
        #pink:Error;
        kill;
    endswitch
}

@enduml