syntax = "proto3";

option csharp_namespace = "QxM.HardwareGateway";

package qxm.ics;

import "Protos/command_spec.proto";

message SendCommandRequest {
  // Client generated idempotency key. If resent it should not cause duplicate execution.
  string idempotency_key = 1;
  // Used to correlate logs/traces across services.
  string correlation_id = 2;
  // Target device address.
  uint32 address = 3;
  // Command specification.
  CommandSpec spec = 4;
  // Client desired timeout for execution (gateway will enforce an upper-bound)
  uint32 timeout_ms = 5;
}